name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: test
        run: yarn && yarn test
      - name: report
        run: yarn test:report
        env:
          CI: true
